global_costmap:

  global_frame: /map
  # robot_base_frame: base_footprint
  update_frequency: 5.0
  static_map: true
  map_type: costmap


  plugins:
  
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: obstacles_layer,         type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}