#obstacle_layer:
observation_sources: my_laser_2
my_laser_2: {sensor_frame: /robot2/base_scan, data_type: LaserScan, topic: /robot2/scan, marking: true, clearing: true}

DWAPlannerROS:
  # global_frame_id: /robot2/odom
  global_frame_id: /map


global_costmap:

  robot_base_frame: /robot2/base_footprint

local_costmap:

  # global_frame: /robot2/odom
  global_frame: /map
  robot_base_frame: /robot2/base_footprint