obstacle_layer:
  observation_sources: hokuyo_laser
  hokuyo_laser: {sensor_frame: /robot1/base_scan, data_type: LaserScan, topic: /robot1/scan, marking: true, clearing: true}

DWAPlannerROS:
  global_frame_id: /robot1/odom

global_costmap:

  robot_base_frame: /robot1/base_footprint

local_costmap:

  global_frame: /robot1/odom
  robot_base_frame: /robot1/base_footprint