# static_map - True if using existing map

global_costmap:
  global_frame: /map
  robot_base_frame: /robot2/base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  resolution: 0.05
  static_map: true
  width: 40.0
  height: 40.0
  map_type: costmap
  transform_tolerance: 10